config/routes.rb
Blog::Application.routes.draw do
  get "welcome/index"

  resources :articles

  root :to => 'welcome#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :text, :title
  validates :title, presence: true,
            length: {minimum: 5}

  def update_values(dict)
    self.text = dict[:text]
    self.title = dict[:title]
    save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end
  
  def new
    @article = Article.new
  end

  def create
    #render plain: params[:article].inspect
    #render plain: params[:article].inspect

    @article = Article.new(params[:article])

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
    #puts "\n" * 20
    #puts @article.to_hash
    #redirect_to '/articles/show'
    
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update_values(params[:article])
      redirect_to @article
    else
      render 'edit'
    end
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    print 'Welcome controller visited.', "\n"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= form_for :article, url: "/articles/update/"+@article.id.to_s, method: :POST do |f| %>
<% if @article.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@article.errors.count, "error") %> prohibited
    this article from being saved:</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :text %><br>
  <%= f.text_area :text %>
</p>

<p>
  <%= f.submit %>
</p>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>listing articles</h1>
<%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
  </tr>

  <% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.text %></td>
    <td><%= link_to 'Show', article_path(article) %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
  </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<%= form_for :article, url: articles_path do |f| %>
<% if @article.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@article.errors.count, "error") %> prohibited
    this article from being saved:</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :text %><br>
  <%= f.text_area :text %>
</p>

<p>
  <%= f.submit %>
</p>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <% for line in @article.text.split("\n") %>
      <% for sec in 0...(line.size - line.lstrip().size) %>
        &nbsp;
      <% end %>
    <%= line.lstrip  %><br>
  <% end %>
</p>

<%= link_to 'Back', articles_path %>
| <%= link_to 'Edit', edit_article_path(@article) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1> Hello, Rails! </h1>
<%= link_to 'My Blog', controller: 'articles' %>